server:
  port: 8080

spring:
  application:
    name: ecommerce

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    schemas: shoppingDB
  datasource:
    url: jdbc:postgresql://localhost:5432/shoppingDB
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Dancinglight@30
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect

  data:
    logging:
      enabled: true

